#!/usr/bin/env node
// PreToolUse guard: refuse edits to files that must not be rewritten by an agent.
// Exit 2 blocks the tool call and returns the reason to Claude.

import path from "path";

const PROTECTED = [
  { re: /(^|\/)(pnpm-lock\.yaml|package-lock\.json)$/, why: "lockfiles are generated; run the package manager instead" },
  { re: /(^|\/)LICENSE$/, why: "licence text is not edited by an agent" },
  { re: /(^|\/)\.next\//, why: ".next is build output" },
  { re: /(^|\/)node_modules\//, why: "node_modules is vendored dependency code" },
  { re: /(^|\/)next-env\.d\.ts$/, why: "next-env.d.ts is generated by Next.js" },
  { re: /\.tsbuildinfo$/, why: "tsbuildinfo is build output" },
  { re: /(^|\/)\.claude\/settings\.local\.json$/, why: "settings.local.json holds your personal permissions; use .claude/settings.json for shared config" },
  { re: /(^|\/)\.claude\/\.session-edits\//, why: "the session edit log is written by hooks" },
];

let input = "";
process.stdin.on("data", (c) => (input += c));
process.stdin.on("end", () => {
  let payload = {};
  try { payload = JSON.parse(input || "{}"); } catch { process.exit(0); }

  const target =
    payload?.tool_input?.file_path ??
    payload?.tool_input?.notebook_path ??
    payload?.tool_input?.path;
  if (!target) process.exit(0);

  const cwd = payload.cwd || process.env.CLAUDE_PROJECT_DIR || process.cwd();
  const rel = path.relative(cwd, path.resolve(cwd, target)) || target;

  for (const rule of PROTECTED) {
    if (rule.re.test(rel) || rule.re.test(target)) {
      process.stderr.write(
        `Blocked: ${rel} is a protected path.\nReason: ${rule.why}.\n` +
        `If this edit is genuinely needed, ask the user to make it or to relax ` +
        `scripts/hooks/protect-paths.mjs.\n`);
      process.exit(2);
    }
  }
  process.exit(0);
});
